name: Check and publish preview releases

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write # used to upload artifacts to codecov

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # see https://docs.codecov.com/docs/environment-specific-requirements#github-actions

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Build
        run: pnpm build --env-mode=loose

  build-storybook:
    name: Build internal Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Build
        run: pnpm build-storybook

  test:
    name: Test @storybook/mcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Run tests with coverage
        run: pnpm test --coverage --reporter=junit --outputFile=test-report.junit.xml

      - name: Upload test and coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: |
            coverage/
            test-report.junit.xml

  typecheck:
    name: Type check @storybook/addon-mcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Run type checking
        run: pnpm turbo run typecheck

  release-preview:
    name: Publish preview releases
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Build
        run: pnpm build

      - name: Publish preview release
        run: pnpm pkg-pr-new publish --pnpm --compact --no-template './packages/*'

  format-check:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Check formatting
        run: pnpm format --check

  collect-coverage:
    name: Collect coverage and test results
    runs-on: ubuntu-latest
    needs: [test]
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # see https://docs.codecov.com/docs/environment-specific-requirements#github-actions

      - name: Download @storybook/addon-mcp coverage
        uses: actions/download-artifact@v4
        with:
          name: test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          fail_ci_if_error: true
          files: |
            coverage/lcov.info
      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          use_oidc: true
          fail_ci_if_error: true
          files: |
            test-report.junit.xml
