name: Check

on:
  pull_request:
  push:
    branches:
      - main
      - next

permissions:
  id-token: write # used to upload artifacts to codecov

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: guergeiro/pnpm:24-10-slim
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 2 # see https://docs.codecov.com/docs/environment-specific-requirements#github-actions

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-


      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v2.3.2

      - name: Install dependencies
        if: ${{ inputs.install-offline != 'true' }}
        shell: bash
        run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts

      - name: Prune pnpm store
        shell: bash
        run: pnpm prune store

      - name: Build
        run: pnpm turbo run build

  build-storybook:
    name: Build internal Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Build
        run: pnpm turbo run build-storybook

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 2 # see https://docs.codecov.com/docs/environment-specific-requirements#github-actions

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Run tests with coverage
        run: pnpm turbo run test:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          use_oidc: true
          fail_ci_if_error: true
          files: |
            coverage/lcov.info

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1.1.1
        if: always()
        with:
          use_oidc: true
          fail_ci_if_error: true
          files: |
            test-report.junit.xml

  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Run type checking
        run: pnpm turbo run typecheck

  publint:
    name: Publint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Run linting
        run: pnpm turbo run publint

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Run linting
        run: pnpm turbo run lint:ci

  format-check:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: Check formatting
        run: pnpm turbo run format:check
